frontend/web-frontend/BoerBert.css, frontend/web-frontend/BoerBert.html
header en footer gemaakt binnen html en css met navbar en buttons
=> header en footer html/css

frontend/web-frontend/BoerBert.css
de footer is klaar er moet nog gewoon woorden eraan verandert worden in de html en nu miss ik alleen de body
=> footer klaar

TI/RFID-platformio/src/main.cpp
=> Nfc dev module

TI/RFID-platformio/src/main.cpp, TI/RFID-platformio/src/pins.h
=> I did things :)))

TI/RFID-platformio/src/main.cpp
Samenwerken aan code naast elkaar, onnodig om git te gebruiken.
Sync met main.
=> Coen en tim 18 nov

backend/api/customers/customers.js, backend/db.js
=> customer basics toegevoegd

TI/RFID-platformio/src/main.cpp, backend/api.js, backend/api/README.md, backend/api/generic/index.js, backend/api/index.js, backend/util.js
=> Readers routes

backend/api/readers/README.md, backend/api/readers/index.js, backend/db.js
- Update all reader routes with correct error handling
=> Get all readers api

backend/config.js, backend/util.js
- add timestamp to logging helper functions in the dev environment
- resolve circular dependency in config
- log the current environment on startup in config to (hopefully) remind myself to switch to prod
=> Logging add timestamp

backend/CONVENTIONS.md
=> add a code conventions document

TI/RFID-platformio/src/config.h, TI/RFID-platformio/src/main.cpp, TI/RFID-platformio/t.js
- Implement and refine the call to imalive from the reader.
- Calculate battery percentage with lookup table because of the nonlinear discharge graph
- Send battery percentage in the request
=> Update battery server once day

backend/util.js
update log functions to use timestamp instead of date (small error)
=> change datae to time stamp in console

backend/.gitignore, backend/api.js, backend/api/auth/README.md, backend/api/auth/index.js, backend/db.js, backend/package-lock.json, backend/package.json
=> added initialization routes for authentication

backend/api/auth/index.js, backend/api/booking/booking.js, backend/db.js
- Refactor booking and auth route code to remove raw queries from the route code
=> Move db call from route to function

backend/api/booking/booking.js, backend/api/cards/cards.js, backend/db.js
- join with authlevels table when GETting /getExtensiveCards
=> Getextensivecards join auth level

backend/db.js
- booking data now shows up in /getAllExtensiveCards
=> fix booking data not showing up in query

backend/api/cards/cards.js
- id is now generated on the server (formerly in request)
- link with booking is now optional (formerly NOT NULL)
=> fix insert card

backend/api/booking/booking.js, backend/scripts/sql/db_init.sql
- you can now get all bookings
=> Get all bookings

backend/api/booking/README.md, backend/api/booking/booking.js, backend/db.js
- getAllBookings sql was broken, names were wrong. Fixed with proper SELECT's
=> Fix get bookings sql

backend/api/cards/README.md
- Accidentally wrote insertCard documentation at getAllCards, fixed
=> fixed documentation misplacement

backend/api/cards/README.md, backend/db.js
- add customer info to getAllExtensiveCards
- update corresponding documentation
=> Customer info extensive cards

backend/TODO, backend/demo.js
=> Remove demo

backend/config.js, backend/docgen/doc.js, backend/package.json
- add configuration in environment variables to enable/disable documentation generation
=> added config options for doc generation

backend/api/auth/DOCS.md, backend/api/booking/DOCS.md, backend/api/cards/DOCS.md, backend/api/customers/DOCS.md, backend/api/readers/DOCS.md, backend/docgen/DOCS.md, backend/docgen/doc.js
=> change doc code lang to javascript

backend/api.js
=> use cors in API

frontend/web-frontend/BoerBert.css
- remove annoying white border from main page
=> fix body margin

backend/api/index.js, backend/util.js
=> fixed log path

backend/api.js, backend/db.js
- changes so the code runs on the server
=> Server diagnose

backend/api.js, backend/degroeneweide.service, frontend/web-frontend/reserveren_mail.js
- add unit file for backend daemon
=> Backend daemon

backend/apikey.js, backend/config.js
- add config option to enable/disable api key
=> add api key use toggle

backend/api/README.md, backend/api/index.js
=> update api root docs

backend/index.js, backend/util.js
=> Trust proxy

backend/resources/confirmationmailcontent.html
- added css styling to the confirmation mail
=> Style mail

backend/index.js
=> delete rate limit logging

backend/api/auth/index.js, backend/api/cards/cards.js, backend/api/customers/customers.js, backend/api/index.js, backend/apiKey.js, backend/index.js, backend/mailer.js, backend/util.js, frontend/web-frontend/reserveren.js
- removed unwanted console.logs's
- moved somewhat important logs to new debug_log function
=> Remove excessive logs

backend/util.js
=> fixed wrong variable name crash

backend/apiKey.js, backend/mailer.js, frontend/web-frontend/reserveren.js
=> added missing debug_log imports

backend/resources/confirmationmailcontent.html, backend/util.js
this is why you test before pushing to prod
=> Remove captcha log

frontend/web-frontend/mail_confirmed.css, frontend/web-frontend/mail_confirmed.html
css design toegevoegd aan de mail confirm pagina ( niet gechecked als het responsive is tho )
=> css toegevoegd met een pop up design

frontend/web-frontend/eula.css, frontend/web-frontend/eula.html, frontend/web-frontend/mail_confirmed.css, frontend/web-frontend/mail_confirmed.html
last min terug btn om terug te gaan
=> Last min btn
